### ISSUE TITLE
Improve accessibility of datatable

### ISSUE THREAD

**Issue by mairatma** [metal/metal-datatable#1]
It's not currently possible to use metal-datatable with a screen reader. It's also not possible to use it only via the keyboard.

We should make sure that both these use cases work. It's not simple work though, we need to find a keyboard solution that will work well for the user, without taking to much time to accomplish the necessary work, which can be hard on big tables for example.

**Comment by mairatma** [comment]
@jbalsas, @juliocamarero, since you have more experience working on accessibility, do you have any ideas on the best approach to use with datatables like these? I researched but couldn't find a lot of consistent material for this, just different ideas spread out through the web.

One option involved allowing the user to tab to each table, only entering its rows after hitting **ENTER** for example, and then only entering the columns after hitting **ENTER** again, and so on. I wasn't sure if that's a known pattern for tables though, since I only saw one place mentioning it, and with very little details. If it's not known how would screen reader users know that this is how the component would behave? Should we add instructions in the table's **aria-label** or something like that? This seems hard to implement too, specially since we can have nested tables in this component, so wanted to be sure of the best approach before trying to work on it.

Let me know what you think :)

**Comment by mairatma** [comment]
Screenshot with a few examples of this component's output:

<img width="917" alt="screen shot 2016-08-11 at 3 29 11 pm" src="https://cloud.githubusercontent.com/assets/5216049/17600314/53ddd79e-5fd9-11e6-8aa8-12a8290635f0.png">

Note that entries that say something like **Object, 2 items** can be clicked to expand/collapse another table with data.

**Comment by mairatma** [comment]
I've found a more reliable source related to how this should work: https://www.w3.org/TR/wai-aria-practices/#grid. It says it needs a review, but seems like a known standard for this at least, so we could follow it.

**Comment by juliocamarero** [comment]
Thanks for taking care of this @mairatma! The link you shared seems perfect. Even if it needs to be reviewed, it won't probably change a lot and it's at list from the W3C. 👍

**Comment by jbalsas** [comment]
Hey @mairatma, I agree with @juliocamarero that the W3C is more than enough ☺️ 

I'd only try to add http://webaim.org/techniques/tables/data to the mix. Basically the part regarding the use of the `scope` attribute to properly associate the cells with their headers. I couldn't find it in the W3C grid recommendations and I don't see us using it in our implementation. Might be worth a second look.

Thanks a lot!

**Comment by mairatma** [comment]
Thanks guys, I'll follow your advice :)

**Comment by mairatma** [comment]
Done :)
