### ISSUE TITLE
Demo doesn't work

### ISSUE THREAD

**Issue by ssmith353** [metal/metal-datatable#3]
Errors in the console: 

`16:39:31.079 incremental-dom-cjs.js:1398 Uncaught ReferenceError: exports is not defined
    at incremental-dom-cjs.js:1398
    at incremental-dom-cjs.js:1419
    at Datatable.js:521`

`16:39:31.090 index.html:117 Uncaught TypeError: metal.Datatable is not a constructor
    at index.html:117`

**Comment by jbalsas** [comment]
Hey @eduardolundgren, yeah, we need to update the demos. @vbence86 has been updating the `metal.js` examples with @Robert-Frampton. We will do a sweep of all modules with demos this week to update them properly.

**Comment by jbalsas** [comment]
Hey @ssmith353, I've sent https://github.com/metal/metal-datatable/pull/4 with the updated build to `webpack`.

**Comment by robframpton** [comment]
Merged #4
